# Generated by Django 4.1.2 on 2023-12-13 09:04

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Method',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('css_color', models.TextField(blank=True, null=True)),
                ('css_price_net', models.TextField(blank=True, null=True)),
                ('css_price_gross', models.TextField(blank=True, null=True)),
                ('address', models.URLField(blank=True, null=True)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.method')),
            ],
            options={
                'db_table': 'WebSite',
            },
        ),
        migrations.CreateModel(
            name='SpiderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.website')),
            ],
            options={
                'db_table': 'SpiderProduct',
            },
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField()),
                ('datetime', django_jalali.db.models.jDateTimeField()),
                ('price_net', models.PositiveIntegerField(blank=True, null=True)),
                ('price_gross', models.PositiveIntegerField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('percent_change', models.FloatField(blank=True, null=True)),
                ('spider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spiderproduct')),
            ],
            options={
                'db_table': 'Extract',
            },
        ),
    ]
